create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,plan text not null default 'free',created_at timestamptz default now());
create table if not exists public.conversations(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null default 'New conversation',model text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.conversations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null,content text not null,metadata jsonb default '{}',created_at timestamptz default now());
create table if not exists public.projects(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,description text default '',instructions text default '',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.memories(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,content text not null,source text default 'user',created_at timestamptz default now());
create table if not exists public.assistants(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,description text default '',instructions text default '',model text,tools jsonb default '[]',created_at timestamptz default now());
create table if not exists public.usage_events(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,event_type text not null,units int default 1,metadata jsonb default '{}',created_at timestamptz default now());
create table if not exists public.api_keys(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,key_hash text not null,key_prefix text not null,created_at timestamptz default now(),revoked_at timestamptz);
